#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.4.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 100)  # TODO: edit here
    w = [None for _ in range(N)]
    v = [None for _ in range(N)]
    W = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(N):
        w[i] = random.randint(1, W)  # TODO: edit here
        v[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, W)
    for i in range(N):
        print(w[i], v[i])

if __name__ == "__main__":
    main()
